keys:
  - &primary age1eug56luat7x5dz8rp4uqh9gn2qp8mkhpcn9ucmzzl34nclsp6fyqwfr7cq
  - &laptop age1mcxhmdnjvw25plt66tmljtzs4l0wm56ru8nu072mtl2rz0n2vshs7df8dl
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *primary
      - *laptop
