"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$all"

[directory]
style = "bold blue"
truncate_to_repo = true
truncation_symbol = "» "

[line_break]
disabled = true

[nix_shell]
format = "[󱄅](bold blue) "

[cmd_duration]
format = "[$duration](style) "

[git_branch]
format ="[@$branch(:$remote_branch)]($style) "

[git_status]
format = "$conflicted$behind$ahead$diverged"
conflicted = "[✖](bold red)"

[package]
disabled = true

[rust]
format ="[$symbol($version )]($style)"

[nodejs]
format ="[$symbol($version )]($style)"

[cmake]
disabled = true

[scala]
disabled = true
